[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
generic-camera = { path = "../../generic_camera" }
image = "0.25.2"
refimage = { path = "../../refimage", features = ["image"] }
serde = "1.0.210"
serde_json = "1.0.128"
